name: Build & Release WordPress Plugin

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Extract version from plugin file
      id: get_version
      run: |
        PLUGIN_MAIN_FILE="wp-manager-connector/wp-manager-connector.php"
        VERSION=$(grep -oP 'Version:\s*\K([0-9]+\.[0-9]+\.[0-9]+)' "$PLUGIN_MAIN_FILE")
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"

    - name: Create plugin ZIP
      run: |
        mkdir -p dist
        zip -r "dist/wp-manager-connector-v${{ steps.get_version.outputs.version }}.zip" wp-manager-connector -x "*.git*" ".github/*" "dist/*"

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: wp-manager-connector
        path: dist/*.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: dist/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
