name: Build WordPress Plugin ZIP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Extract version from plugin file
      id: get_version
      run: |
        VERSION=$(grep -oP 'Version:\s*\K([0-9]+\.[0-9]+\.[0-9]+)' perfex-wp-manager.php)
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"

    - name: Create plugin ZIP
      run: |
        mkdir -p dist
        zip -r "dist/perfex-wp-manager-v${{ steps.get_version.outputs.version }}.zip" . -x "*.git*" ".github/*" "dist/*"

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: perfex-wp-manager
        path: dist/*.zip
